### ISSUE TITLE
Allow Render To Include Generated HTML

### ISSUE THREAD

**Issue by joefitzgerald** [atom/etch#34]
```javascript
let createMarkup = () => { return {__html: '<span style="text-decoration: blink;">Because who uses the blink tag?</span>'} }
return (
  <div
    className='content'
    dangerouslySetInnerHTML={createMarkup()}
  />
)
```

Renders `<div class="content" />`.

```javascript
let markup = '<span style="text-decoration: blink;">Because who uses the blink tag?</span>'
return (
  <div className='content'>{markup}</div>
)
```

Renders `<div class="panel-body padded">&lt;span style="text-decoration: blink;"&gt;Because who uses the blink tag?&lt;/span&gt;</div>`

If one wishes to generate dynamic HTML content and emit it in an etch view, they cannot. Would there be a way to allow this?

**Comment by BinaryMuse** [comment]
If I'm not mistaken I think you can set `innerHTML="...html string"`

**Comment by BinaryMuse** [comment]
Note this has to do with how React/virtual-dom processes node properties and not JSX.

**Comment by joefitzgerald** [comment]
@BinaryMuse but can I use a function that will be evaluated at runtime (and not during transpilation) using the technique you described?

**Comment by joefitzgerald** [comment]
Answer: yes, it is evaluated correctly. Thankyou!
