### ISSUE TITLE
JSX Dynamic Component Name

### ISSUE THREAD

**Issue by ivankravets** [atom/etch#39]
Hi,

Would be thankful for any hints how to render Dynamic Components. Similar to [this question](http://stackoverflow.com/questions/26518629/dynamically-rendering-a-react-component).

I tried different options but it doesn't work after `etch.update(this)`.

Use case

```js
class MyComponent {
  constructor (properties) {
    this.properties = properties
    etch.initialize(this)
  }

  renderDynComponent () {
    if (case1) {
      return <DynComponent1 />
    }
    else if (case2) {
      return <DynComponent2 />
    }
    return <DynComponentDefault />
  }

  render () {
    return <div>{this.renderDynComponent()}</div>
  }
}
```

Thanks!

**Comment by BinaryMuse** [comment]
Hi, @ivankravets,

I wrote the following test case and it works:

```javascript
  it('updates dynamic components', async () => {
    class DynComponent1 {
      constructor () { etch.initialize(this) }
      update () { return etch.update(this) }
      render () { return <div>DynComponent1</div> }
    }

    class DynComponent2 {
      constructor () { etch.initialize(this) }
      update () { return etch.update(this) }
      render () { return <div>DynComponent2</div> }
    }

    class DynComponentDefault {
      constructor () { etch.initialize(this) }
      update () { return etch.update(this) }
      render () { return <div>DynComponentDefault</div> }
    }

    class MyComponent {
      constructor (properties) {
        this.properties = properties
        etch.initialize(this)
      }

      update (properties) {
        this.properties = properties
        return etch.update(this)
      }

      renderDynComponent () {
        if (this.properties.selection === 1) {
          return <DynComponent1 />
        } else if (this.properties.selection === 2) {
          return <DynComponent2 />
        }
        return <DynComponentDefault />
      }

      render () {
        return <div>{this.renderDynComponent()}</div>
      }
    }

    const component = new MyComponent({selection: 1})
    expect(component.element.textContent).to.equal('DynComponent1')
    await component.update({selection: 2})
    expect(component.element.textContent).to.equal('DynComponent2')
    await component.update({selection: 3})
    expect(component.element.textContent).to.equal('DynComponentDefault')
  })
```

Did you forget to implement an `update` somewhere by chance?

**Comment by ivankravets** [comment]
> Did you forget to implement an update somewhere by chance?

I tried to don't re-invent a wheel and reused [this abstract class](https://github.com/atom/about/blob/master/lib/etch-component.js) by @mnquintana. Maybe a problem is hidden here?

What I can confirm:

1. First "render()" works a good. I see a right content of `renderDynComponent` in DOM.
2. Second `this.update({selection: 2})` inside `MyComponent` that extends `EtchComponent` calls `DynComponent2::render()`` (I have some prints...) but in DOM it looks EMPTY.

---

1. `<div>{this.renderDynComponent()}</div>` === `<div>REAL_CONTENT</div>`
2. `<div>{this.renderDynComponent()}</div>` === `<div></div>`

Do you have any ideas?

**Comment by nathansobo** [comment]
@ivankravets It could be an issue with calling `etch.destroy` in the component that is replaced. There's a challenge related to integrating with the virtual-dom library that makes Etch's default behavior of having `etch.destroy` remove the element from the DOM break this use case. Try passing an argument of `true` (`etch.destroy(true)`) in your component's destroy method. This will suppress the removal of the DOM element from the document and might help here.

**Comment by BinaryMuse** [comment]
It should be `etch.destroy(this, true)` if I recall

**Comment by nathansobo** [comment]
Yes that. Thanks!

**Comment by ivankravets** [comment]
@nathansobo @BinaryMuse Tried, it didn't help.

Do you have other solution for this use case? I have a menu similar to "atom's settings". Also, I have "placeholder"(pane) where a related component of each menu item should be rendered. Each item in a menu has own Etch component.

Please sorry, I'm not keen in Atom development. I understand that I can render ALL components and hide them via `display: none`. For me, it looks like a very strange solution.

Thanks!

**Comment by BinaryMuse** [comment]
@ivankravets Without a more specific failing case, I'm not sure there's much we can do to help. It's likely that a DOM node is being modified in some way that Etch can't reconcile, but it's hard to say where or how without a more specific example.

**Comment by ivankravets** [comment]
@BinaryMuse This is a good example

* https://github.com/atom/etch/issues/39#issue-195941938

1. Try to create a few components that extend [this abstract class](https://github.com/atom/about/blob/master/lib/etch-component.js)
2. Implement `render` of main component as 
```js
  renderDynComponent () {
    if (case1) {
      return <DynComponent1 />
    }
    else if (case2) {
      return <DynComponent2 />
    }
    return <DynComponentDefault />
  }

  render () {
    return <div>{this.renderDynComponent()}</div>
  }
```
3. Chagne `caseN` condition and try to `this.update()` in main component.
