### ISSUE TITLE
CoffeeScript support

### ISSUE THREAD

**Issue by lee-dohm** [atom/etch#4]
I was playing around with this again and I thought that what could be cool for CoffeeScript is something like this:

```coffee
# Private: Registers the custom element with the DOM.
registerElement: ->
  etch.defineElement 'div',
    render: (html) ->
      html.div {className: 'soft-wrap-status inline-block'},
        html.a {href: '#'}, 'Wrap'

    initialize: ->
      this
```

The `html` object would just need to be an object with a bunch of helpers on it that look like this (except in ES6):

```coffee
div = (properties, children...) ->
  dom 'div', properties, children

a = (properties, children...) ->
  dom 'a', properties, children
```

I've [tested this strategy](https://github.com/lee-dohm/soft-wrap-indicator/blob/ld-etch/lib/soft-wrap-indicator.coffee#L6-L10) with just using hard coded helpers (not passing parameters through render) and it seems to work.

**Comment by mark-hahn** [comment]
Check out npm teacup.  Teacup is a spin-off of an old module I did.

**Comment by lee-dohm** [comment]
This isn't a priority anymore for Etch. I looked at Teacup before and it looks very cool!
