### ISSUE TITLE
How to pass attribute for element without value?

### ISSUE THREAD

**Issue by ivankravets** [atom/etch#40]
Hi,

I tried different options but without success. An Atom's Text Editor has `mini` attribute. What is a correct syntax to set it? I use 
```jsx
<atom-text-editor mini={true}>Hello</atom-text-editor>
```

Thanks.

**Comment by nathansobo** [comment]
You should be able to instantiate an editor directly via its constructor in your JSX rather than via that tag name. Do something like this...

```
// in your imports section
import {TextEditor} from 'atom'

// in your JSX
<TextEditor mini={true} =>
```

**Comment by ivankravets** [comment]
Thanks a lot! It works.
