### ISSUE TITLE
Example for using etch for a standalone webapp

### ISSUE THREAD

**Issue by luisschubert** [atom/etch#56]
I am wanting to use etch for a standalone webapp instead of for electron or atom and am having trouble getting started. Are there any examples available aside from the ones on the README that illustrate how to use etch? @BinaryMuse, @nathansobo, @as-cii

**Comment by lloiser** [comment]
What's your problem exactly? Do you get any errors?
The README already provides enough information https://github.com/atom/etch#overview

**Comment by nathansobo** [comment]
@luisschubert Hey, sorry you're having trouble. I don't personally have the bandwidth to produce documentation for this library that's as extensive as some of the other libraries out there. For now, you may be better off giving something like React or Angular a try if you need more extensive docs and examples. Wish I could help more but there just isn't enough time.
