### ISSUE TITLE
standalone build

### ISSUE THREAD

**Issue by larkin** [atom/etch#58]
I put together a standalone umd build for browser usage at https://www.npmjs.com/package/etch-standalone.  I realized after the fact that this is probably counter productive and I should just delete that package and contribute my changes here.

You see any problem to include the basic build steps from https://github.com/larkin/etch-standalone/blob/master/package.json#L7-L9 to produce a singular minified build file?  Happy to open a PR & trash the package I just published.

**Comment by nathansobo** [comment]
@larkin, sure thing. I'm open to publishing a standalone build. Thanks for offering!
