### ISSUE TITLE
what's the performance like?

### ISSUE THREAD

**Issue by capaj** [atom/etch#59]
I'd love to see some benchmarks comparing etch to react, inferno or other vdom libs.
Can anyone add some?
Or maybe add etch to https://github.com/krausest/js-framework-benchmark ?

**Comment by nathansobo** [comment]
@capaj Would you be interested in trying it?

**Comment by lloiser** [comment]
ping: https://github.com/krausest/js-framework-benchmark/pull/234
here are some preliminary results: https://jsfiddle.net/lloiser/hjndzndk/

**Comment by nathansobo** [comment]
It looks like we're doing okay. When that PR get's merged would you be down to add it to our README?
