### ISSUE TITLE
Escape html

### ISSUE THREAD

**Issue by mateuspv** [atom/etch#63]
Hi, I would like to now if there's a way of scape html,
I'm parsing a markdown and would like to insert the content inside my etch component
Something like: https://stackoverflow.com/questions/39758136/render-html-string-as-real-html-in-a-react-component
Thanks

**Comment by lierdakil** [comment]
Sorry, I don't understand. Do you want to escape HTML (i.e. replace `<` with `&lt;` etc) or do you want to render an HTML string?

**Comment by mateuspv** [comment]
Hi,
Render an html string as etch html,
I'm parsing a markdown and it html result should be inside my etch component.

**Comment by lierdakil** [comment]
Set `innerHTML` property on an ordinary HTML element. E.g.
```jsx
<div innerHTML={yourHtmlString} />
```
See, e.g. [here](https://github.com/atom-haskell/ide-haskell-hoogle/blob/master/src/hoogle-doc-view.tsx#L60) for a more complete example (it's typescript, but I don't think it matters much)

**Comment by nathansobo** [comment]
Thanks @lierdakil. I'm going to close this out since we have a solution.
