### ISSUE TITLE
Etch was removed from the benchmark link

### ISSUE THREAD

**Issue by UziTech** [atom/etch#87]
Is this project dead or just feature complete?

https://github.com/krausest/js-framework-benchmark#2020-7-9

**Comment by aminya** [comment]
Since we have made some commits, we can add the framework back. I made a PR here: https://github.com/krausest/js-framework-benchmark/pull/792

**Comment by aminya** [comment]
etch 0.14.1 is now in the benchmark! 
https://rawgit.com/krausest/js-framework-benchmark/master/webdriver-ts-results/table.html
